//
//  Equation.swift
//
//  Created by Evan Anderson on 4/6/23.
//

import Foundation
import HugeNumbers

enum Equation {
    
    enum Energy {
        /// Calculates the power (energy per unit time) converted from electrical energy to thermal energy (direct current)
        /// - Parameters:
        ///     - current: current travelling through the resistor or other element
        ///     - resistance: electrical resistance
        /// - Returns: power of heating generated by an electrical conductor
        static func joule_heating_dc(current: HugeFloat, resistance: HugeFloat) -> HugeFloat {
            return (current * current) * resistance
        }
        /// Alternating Current.
        static func joule_heating_ac(current: HugeFloat, resistance: HugeFloat) {
        }
    }
    
}
